services:
  redis:
    image: redis:7.2.2
    ports:
      - "6379:6379"

  ########## AUDIO MODALITY SERVICES
  pre-processing-audio:
    image: some.registry.com/xr2learn-enablers/pre-processing-audio:latest
    volumes:
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
      - "./outputs:/app/outputs"
      - "./datasets:/app/datasets"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python pre_processing_audio_modality/preprocess.py

  handcrafted-features-generation-audio:
    image: some.registry.com/xr2learn-enablers/handcrafted-features-generation-audio:latest
    volumes:
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
      - "./outputs:/app/outputs"
      - "./datasets:/app/datasets"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python handcrafted_features_extraction_audio_modality/generate_features.py

  ssl-audio:
    image: some.registry.com/xr2learn-enablers/ssl-audio:latest
    volumes:
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
      - "./outputs:/app/outputs"
      - "./datasets:/app/datasets"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python ssl_audio_modality/pre_train.py

  ssl-features-generation-audio:
    image: some.registry.com/xr2learn-enablers/ssl-features-generation-audio:latest
    volumes:
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
      - "./outputs:/app/outputs"
      - "./datasets:/app/datasets"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python ssl_features_extraction_audio_modality/generate_features.py

  ed-training-audio:
    image: some.registry.com/xr2learn-enablers/ed-training-audio:latest
    volumes:
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
      - "./outputs:/app/outputs"
      - "./datasets:/app/datasets"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python supervised_audio_modality/train.py

  emotion-classification-audio:
    image: some.registry.com/xr2learn-enablers/ed-classification-audio:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python emotion_classification_audio_modality/predict.py


  ########## BIO-MEASUREMENTS (BM) MODALITY SERVICES
  pre-processing-bm:
    image: some.registry.com/xr2learn-enablers/pre-processing-bm:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python pre_processing_bm_modality/preprocess.py

  handcrafted-features-generation-bm:
    image: some.registry.com/xr2learn-enablers/handcrafted-features-generation-bm:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python handcrafted_features_extraction_bm_modality/generate_features.py

  ssl-bm:
    image: some.registry.com/xr2learn-enablers/ssl-bm:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python ssl_bm_modality/pre_train.py

  ssl-features-generation-bm:
    image: some.registry.com/xr2learn-enablers/ssl-features-generation-bm:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python ssl_features_extraction_bm_modality/generate_features.py

  ed-training-bm:
    image: some.registry.com/xr2learn-enablers/ed-training-bm:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python supervised_bm_modality/train.py

  emotion-classification-bm:
    image: some.registry.com/xr2learn-enablers/ed-classification-bm:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - REDIS_HOST=redis
    command: python emotion_classification_bm_modality/predict.py

########## BODY TRACKING MODALITY SERVICES
  ed-training-body-tracking:
    image: some.registry.com/xr2learn-enablers/ed-training-body-tracking:latest
    volumes:
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
      - "./outputs:/app/outputs"
      - "./datasets:/app/datasets"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
    command: python supervised_body_tracking_modality/train.py

  emotion-classification-body-tracking:
    image: some.registry.com/xr2learn-enablers/emotion-classification-body-tracking:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - REDIS_HOST=redis
    command: python emotion_classification_body_tracking_modality/predict.py
    depends_on:
      - redis

  fusion-layer:
    image: some.registry.com/xr2learn-enablers/fusion-layer:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - PUBLISHER_ON=${PUBLISHER_ON:-false}
      - REDIS_HOST=redis
    command: python multimodal_fusion_layer/predict.py

  personalization-tool:
    image: some.registry.com/xr2learn-enablers/personalization-tool:latest
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: python personalization_tool/suggest_activity_level.py
    depends_on:
      - redis

  dashboard:
    image: some.registry.com/xr2learn-enablers/dashboard:latest
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: python web_app.py
    depends_on:
      - redis
      - personalization-tool
    ports:
      - "8000:8000"