name: Python package

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "cli-tests" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: CLI -- Install dependencies and run tests
        working-directory: ./
        run: |
          pip install -r requirements.txt
          python -m unittest discover -s tests
